name: Android CI

on:
  push:
    paths: 
      - 'android/**'
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]
    paths: 
      - 'android/**'

jobs:
  unit-tests:
    name: Android Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Run unit tests
        run: ./gradlew test
        working-directory: android
    
  instrumented-tests:
    timeout-minutes: 15
    name: Android Instrumented Tests (API ${{ matrix.api-level }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [26, 29]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Enables hardware acceleration for linux runner 
      # to enhance test execution speed
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      
      # - name: AVD cache
      #   uses: actions/cache@v4
      #   id: avd-cache
      #   with:
      #     path: |
      #       ~/.android/avd/*
      #       ~/.android/adb*
      #     key: avd-${{ matrix.api-level }}

      # Caches both the android emulator and snapshot (don't have to create
      # emulator for future runs)
      # - name: Create AVD and generate snapshot for caching
      #   if: steps.avd-cache.outputs.cache-hit != 'true'
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: ${{ matrix.api-level }}
      #     force-avd-creation: false
      #     emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot
      #     disable-animations: false
      #     working-directory: android
      #     script: echo "Generated AVD snapshot for caching."

      # Runs all instrumented Android Tests
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot
          disable-animations: true
          working-directory: android
          script: ./gradlew connectedDebugAndroidTest